// flow-typed signature: 9479b2870ad5c6ebae0adec67c946ba2
// flow-typed version: <<STUB>>/deepstream.io-client-js_v^2.3.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deepstream.io-client-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deepstream.io-client-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deepstream.io-client-js/dist/deepstream' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/deepstream.min' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/client' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/constants/constants' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/constants/merge-strategies' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/default-options' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/event/event-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/message/connection' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/message/message-builder' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/message/message-parser' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/presence/presence-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/record/anonymous-record' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/record/json-path' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/record/list' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/record/record-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/record/record' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/rpc/rpc-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/rpc/rpc-response' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/rpc/rpc' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/utils/ack-timeout-registry' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/utils/listener' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/utils/resubscribe-notifier' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/utils/single-notifier' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/dist/lib/utils/utils' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/Gruntfile' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/jasmine-runner' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/client' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/constants/constants' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/constants/merge-strategies' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/default-options' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/event/event-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/message/connection' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/message/message-builder' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/message/message-parser' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/presence/presence-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/record/anonymous-record' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/record/json-path' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/record/list' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/record/record-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/record/record' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/rpc/rpc-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/rpc/rpc-response' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/rpc/rpc' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/utils/ack-timeout-registry' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/utils/listener' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/utils/resubscribe-notifier' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/utils/single-notifier' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/src/utils/utils' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-node/cli' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-node/command-group' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-node/start' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-node/test' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-page-webpack/index' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-page/js/event-view-model' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-page/js/start' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-page/js/view-model' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-page/lib/ko' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/client/connecting' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/client/events' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/client/presence' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/client/record' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/client/rpc' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/config' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/helper' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/server/step-definition-server' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-specs/steps/server/ws-server' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/mocks/client-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/mocks/message/connection-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/mocks/transport/websocket-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/test-helper/test-helper' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/clientSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/constants/merge-strategiesSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/event/event-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/event/event-listeningSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/message/connectionSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/message/message-builderSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/message/message-parserSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/message/type-conversionSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/presence/presence-handlerDeprecatedSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/presence/presence-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/anonymous-recordSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/json-pathSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/list-change-listenerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/list-spec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-async-Spec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-conflictsSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-handler-listSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-handler-recordSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-listeningSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-reconnectSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-setDataSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-setSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/record/record-subscriptionSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/rpc/rpc-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/rpc/rpc-responseSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/utils/ack-timeout-registrySpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/utils/resubscribe-notifierSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io-client-js/test-unit/unit/utils/utilsSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deepstream.io-client-js/dist/deepstream.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/deepstream'>;
}
declare module 'deepstream.io-client-js/dist/deepstream.min.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/deepstream.min'>;
}
declare module 'deepstream.io-client-js/dist/lib/client.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/client'>;
}
declare module 'deepstream.io-client-js/dist/lib/constants/constants.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/constants/constants'>;
}
declare module 'deepstream.io-client-js/dist/lib/constants/merge-strategies.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/constants/merge-strategies'>;
}
declare module 'deepstream.io-client-js/dist/lib/default-options.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/default-options'>;
}
declare module 'deepstream.io-client-js/dist/lib/event/event-handler.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/event/event-handler'>;
}
declare module 'deepstream.io-client-js/dist/lib/message/connection.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/message/connection'>;
}
declare module 'deepstream.io-client-js/dist/lib/message/message-builder.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/message/message-builder'>;
}
declare module 'deepstream.io-client-js/dist/lib/message/message-parser.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/message/message-parser'>;
}
declare module 'deepstream.io-client-js/dist/lib/presence/presence-handler.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/presence/presence-handler'>;
}
declare module 'deepstream.io-client-js/dist/lib/record/anonymous-record.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/record/anonymous-record'>;
}
declare module 'deepstream.io-client-js/dist/lib/record/json-path.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/record/json-path'>;
}
declare module 'deepstream.io-client-js/dist/lib/record/list.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/record/list'>;
}
declare module 'deepstream.io-client-js/dist/lib/record/record-handler.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/record/record-handler'>;
}
declare module 'deepstream.io-client-js/dist/lib/record/record.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/record/record'>;
}
declare module 'deepstream.io-client-js/dist/lib/rpc/rpc-handler.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/rpc/rpc-handler'>;
}
declare module 'deepstream.io-client-js/dist/lib/rpc/rpc-response.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/rpc/rpc-response'>;
}
declare module 'deepstream.io-client-js/dist/lib/rpc/rpc.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/rpc/rpc'>;
}
declare module 'deepstream.io-client-js/dist/lib/utils/ack-timeout-registry.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/utils/ack-timeout-registry'>;
}
declare module 'deepstream.io-client-js/dist/lib/utils/listener.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/utils/listener'>;
}
declare module 'deepstream.io-client-js/dist/lib/utils/resubscribe-notifier.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/utils/resubscribe-notifier'>;
}
declare module 'deepstream.io-client-js/dist/lib/utils/single-notifier.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/utils/single-notifier'>;
}
declare module 'deepstream.io-client-js/dist/lib/utils/utils.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/dist/lib/utils/utils'>;
}
declare module 'deepstream.io-client-js/Gruntfile.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/Gruntfile'>;
}
declare module 'deepstream.io-client-js/jasmine-runner.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/jasmine-runner'>;
}
declare module 'deepstream.io-client-js/src/client.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/client'>;
}
declare module 'deepstream.io-client-js/src/constants/constants.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/constants/constants'>;
}
declare module 'deepstream.io-client-js/src/constants/merge-strategies.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/constants/merge-strategies'>;
}
declare module 'deepstream.io-client-js/src/default-options.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/default-options'>;
}
declare module 'deepstream.io-client-js/src/event/event-handler.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/event/event-handler'>;
}
declare module 'deepstream.io-client-js/src/message/connection.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/message/connection'>;
}
declare module 'deepstream.io-client-js/src/message/message-builder.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/message/message-builder'>;
}
declare module 'deepstream.io-client-js/src/message/message-parser.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/message/message-parser'>;
}
declare module 'deepstream.io-client-js/src/presence/presence-handler.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/presence/presence-handler'>;
}
declare module 'deepstream.io-client-js/src/record/anonymous-record.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/record/anonymous-record'>;
}
declare module 'deepstream.io-client-js/src/record/json-path.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/record/json-path'>;
}
declare module 'deepstream.io-client-js/src/record/list.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/record/list'>;
}
declare module 'deepstream.io-client-js/src/record/record-handler.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/record/record-handler'>;
}
declare module 'deepstream.io-client-js/src/record/record.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/record/record'>;
}
declare module 'deepstream.io-client-js/src/rpc/rpc-handler.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/rpc/rpc-handler'>;
}
declare module 'deepstream.io-client-js/src/rpc/rpc-response.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/rpc/rpc-response'>;
}
declare module 'deepstream.io-client-js/src/rpc/rpc.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/rpc/rpc'>;
}
declare module 'deepstream.io-client-js/src/utils/ack-timeout-registry.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/utils/ack-timeout-registry'>;
}
declare module 'deepstream.io-client-js/src/utils/listener.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/utils/listener'>;
}
declare module 'deepstream.io-client-js/src/utils/resubscribe-notifier.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/utils/resubscribe-notifier'>;
}
declare module 'deepstream.io-client-js/src/utils/single-notifier.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/utils/single-notifier'>;
}
declare module 'deepstream.io-client-js/src/utils/utils.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/src/utils/utils'>;
}
declare module 'deepstream.io-client-js/test-node/cli.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-node/cli'>;
}
declare module 'deepstream.io-client-js/test-node/command-group.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-node/command-group'>;
}
declare module 'deepstream.io-client-js/test-node/start.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-node/start'>;
}
declare module 'deepstream.io-client-js/test-node/test.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-node/test'>;
}
declare module 'deepstream.io-client-js/test-page-webpack/index.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-page-webpack/index'>;
}
declare module 'deepstream.io-client-js/test-page/js/event-view-model.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-page/js/event-view-model'>;
}
declare module 'deepstream.io-client-js/test-page/js/start.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-page/js/start'>;
}
declare module 'deepstream.io-client-js/test-page/js/view-model.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-page/js/view-model'>;
}
declare module 'deepstream.io-client-js/test-page/lib/ko.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-page/lib/ko'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/client/connecting.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/client/connecting'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/client/events.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/client/events'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/client/presence.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/client/presence'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/client/record.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/client/record'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/client/rpc.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/client/rpc'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/config.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/config'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/helper.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/helper'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/server/step-definition-server.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/server/step-definition-server'>;
}
declare module 'deepstream.io-client-js/test-specs/steps/server/ws-server.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-specs/steps/server/ws-server'>;
}
declare module 'deepstream.io-client-js/test-unit/mocks/client-mock.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/mocks/client-mock'>;
}
declare module 'deepstream.io-client-js/test-unit/mocks/message/connection-mock.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/mocks/message/connection-mock'>;
}
declare module 'deepstream.io-client-js/test-unit/mocks/transport/websocket-mock.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/mocks/transport/websocket-mock'>;
}
declare module 'deepstream.io-client-js/test-unit/test-helper/test-helper.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/test-helper/test-helper'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/clientSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/clientSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/constants/merge-strategiesSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/constants/merge-strategiesSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/event/event-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/event/event-handlerSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/event/event-listeningSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/event/event-listeningSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/message/connectionSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/message/connectionSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/message/message-builderSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/message/message-builderSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/message/message-parserSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/message/message-parserSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/message/type-conversionSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/message/type-conversionSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/presence/presence-handlerDeprecatedSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/presence/presence-handlerDeprecatedSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/presence/presence-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/presence/presence-handlerSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/anonymous-recordSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/anonymous-recordSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/json-pathSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/json-pathSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/list-change-listenerSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/list-change-listenerSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/list-spec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/list-spec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-async-Spec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-async-Spec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-conflictsSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-conflictsSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-handler-listSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-handler-listSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-handler-recordSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-handler-recordSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-listeningSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-listeningSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-reconnectSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-reconnectSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-setDataSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-setDataSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-setSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-setSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/record/record-subscriptionSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/record/record-subscriptionSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/rpc/rpc-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/rpc/rpc-handlerSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/rpc/rpc-responseSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/rpc/rpc-responseSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/utils/ack-timeout-registrySpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/utils/ack-timeout-registrySpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/utils/resubscribe-notifierSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/utils/resubscribe-notifierSpec'>;
}
declare module 'deepstream.io-client-js/test-unit/unit/utils/utilsSpec.js' {
  declare module.exports: $Exports<'deepstream.io-client-js/test-unit/unit/utils/utilsSpec'>;
}
