// flow-typed signature: f3b556e1a034ddd669019876f8747373
// flow-typed version: <<STUB>>/deepstream.io_vgit+https://git@github.com/deepstreamIO/deepstream.io.git#dab0fd740b8efe2c4ddaa9d1dc6531c2e97ec338/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deepstream.io'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deepstream.io' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deepstream.io/bin/deepstream-daemon' {
  declare module.exports: any;
}

declare module 'deepstream.io/bin/deepstream-hash' {
  declare module.exports: any;
}

declare module 'deepstream.io/bin/deepstream-info' {
  declare module.exports: any;
}

declare module 'deepstream.io/bin/deepstream-install' {
  declare module.exports: any;
}

declare module 'deepstream.io/bin/deepstream-service' {
  declare module.exports: any;
}

declare module 'deepstream.io/bin/deepstream-start' {
  declare module.exports: any;
}

declare module 'deepstream.io/bin/installer' {
  declare module.exports: any;
}

declare module 'deepstream.io/jasmine-runner' {
  declare module.exports: any;
}

declare module 'deepstream.io/scripts/details' {
  declare module.exports: any;
}

declare module 'deepstream.io/scripts/license-aggregator' {
  declare module.exports: any;
}

declare module 'deepstream.io/scripts/nexe' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/authentication/file-based-authentication-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/authentication/http-authentication-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/authentication/http-authentication-request' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/authentication/open-authentication-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/cluster/cluster-node' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/cluster/lock-registry' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/cluster/state-registry' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/config/config-initialiser' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/config/file-utils' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/config/js-yaml-loader' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/constants/constants' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/deepstream.io' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/default-options' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/default-plugins/local-cache' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/default-plugins/noop-message-connector' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/default-plugins/noop-storage' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/default-plugins/std-out-logger' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/event/event-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/listen/listener-registry' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/listen/listener-timeout-registry' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/http/connection-endpoint' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/http/server' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/http/socket-wrapper' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/jif-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/message-builder' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/message-distributor' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/message-parser' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/message-processor' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/uws/connection-endpoint' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/message/uws/socket-wrapper' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/config-compiler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/config-permission-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/config-schema' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/config-validator' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/open-permission-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/path-parser' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/rule-application' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/rule-cache' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/rule-parser' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/permission/rules-map' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/presence/presence-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/record/json-path' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/record/record-deletion' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/record/record-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/record/record-request' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/record/record-transition' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/rpc/rpc-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/rpc/rpc-proxy' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/rpc/rpc' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/utils/dependency-initialiser' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/utils/read-message' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/utils/subscription-registry' {
  declare module.exports: any;
}

declare module 'deepstream.io/src/utils/utils' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/client-handler' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/client' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/event' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/listening' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/presence' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/record' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/rpc' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/utils' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/framework/world' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/client/client-definition-step' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/client/connection-steps' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/client/event-steps' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/client/listening-steps' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/client/presence-steps' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/client/record-steps' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/client/rpc-steps' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/client/utils' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/http/http-steps' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/steps/server/step-definition-server' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/tools/cluster' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-e2e/tools/test-logger' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-protocol/run' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-protocol/src/client' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-protocol/src/row' {
  declare module.exports: any;
}

declare module 'deepstream.io/test-protocol/src/server' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/authentication/file-based-authentication-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/authentication/http-authentication-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/authentication/open-authentication-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/bin/installerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/config/config-initialiserSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/config/fileSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/config/js-yaml-loaderSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/deepstreamioSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/default-plugins/local-cacheSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/default-plugins/noop-storageSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/default-plugins/std-out-loggerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/event/event-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/event/event-listeningSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/http/http-endpointSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/http/jif-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/listen/listener-register-local-timeoutsSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/listen/listener-registry-local-load-balancingSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/listen/listener-registry-remote-load-balancingSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/listen/listener-registrySpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/listen/listener-test-utils' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/connection-endpoint-httpsSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/connection-endpointSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/message-builderSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/message-distributorSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/message-parserSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/message-processorSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/permission-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/socket-wrapperSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/message/type-conversionSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/auth-handler-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/authentication-handler-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/closable-logger' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/http-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/logger-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/message-connector-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/perm-handler-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/permission-handler-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/plugin-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/socket-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/socket-wrapper-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/storage-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/mocks/uws-mock' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-compilerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-permission-handler-basicSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-permission-handler-createSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-permission-handler-cross-referenceSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-permission-handler-loadSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-permission-handler-nested-cross-referenceSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-permission-handler-otherSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-permission-handler-record-patchSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/config-validatorSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/open-permission-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/path-parserSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/rule-cacheSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/rule-parserSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/permission/rules-mapSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/presence/presence-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/record/json-pathSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/record/record-deletionSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/record/record-handler-permissionSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/record/record-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/record/record-listeningSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/record/record-requestSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/record/record-transitionSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/record/record-write-acknowledgementSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/rpc/rpc-handler-reroutingSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/rpc/rpc-handlerSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/rpc/rpc-proxySpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/rpc/rpcSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-configs/config-broken' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-configs/config' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-configs/exists-test/a-file' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-helper/custom-logger' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-helper/start-test-server' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-helper/test-helper' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-helper/test-http-server' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-plugins/deepstream.io-connection-http' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/test-plugins/plugin-a' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/utils/dependency-initialiserSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/utils/read-messageSpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/utils/subscription-registrySpec' {
  declare module.exports: any;
}

declare module 'deepstream.io/test/utils/utilsSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deepstream.io/bin/deepstream-daemon.js' {
  declare module.exports: $Exports<'deepstream.io/bin/deepstream-daemon'>;
}
declare module 'deepstream.io/bin/deepstream-hash.js' {
  declare module.exports: $Exports<'deepstream.io/bin/deepstream-hash'>;
}
declare module 'deepstream.io/bin/deepstream-info.js' {
  declare module.exports: $Exports<'deepstream.io/bin/deepstream-info'>;
}
declare module 'deepstream.io/bin/deepstream-install.js' {
  declare module.exports: $Exports<'deepstream.io/bin/deepstream-install'>;
}
declare module 'deepstream.io/bin/deepstream-service.js' {
  declare module.exports: $Exports<'deepstream.io/bin/deepstream-service'>;
}
declare module 'deepstream.io/bin/deepstream-start.js' {
  declare module.exports: $Exports<'deepstream.io/bin/deepstream-start'>;
}
declare module 'deepstream.io/bin/installer.js' {
  declare module.exports: $Exports<'deepstream.io/bin/installer'>;
}
declare module 'deepstream.io/jasmine-runner.js' {
  declare module.exports: $Exports<'deepstream.io/jasmine-runner'>;
}
declare module 'deepstream.io/scripts/details.js' {
  declare module.exports: $Exports<'deepstream.io/scripts/details'>;
}
declare module 'deepstream.io/scripts/license-aggregator.js' {
  declare module.exports: $Exports<'deepstream.io/scripts/license-aggregator'>;
}
declare module 'deepstream.io/scripts/nexe.js' {
  declare module.exports: $Exports<'deepstream.io/scripts/nexe'>;
}
declare module 'deepstream.io/src/authentication/file-based-authentication-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/authentication/file-based-authentication-handler'>;
}
declare module 'deepstream.io/src/authentication/http-authentication-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/authentication/http-authentication-handler'>;
}
declare module 'deepstream.io/src/authentication/http-authentication-request.js' {
  declare module.exports: $Exports<'deepstream.io/src/authentication/http-authentication-request'>;
}
declare module 'deepstream.io/src/authentication/open-authentication-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/authentication/open-authentication-handler'>;
}
declare module 'deepstream.io/src/cluster/cluster-node.js' {
  declare module.exports: $Exports<'deepstream.io/src/cluster/cluster-node'>;
}
declare module 'deepstream.io/src/cluster/lock-registry.js' {
  declare module.exports: $Exports<'deepstream.io/src/cluster/lock-registry'>;
}
declare module 'deepstream.io/src/cluster/state-registry.js' {
  declare module.exports: $Exports<'deepstream.io/src/cluster/state-registry'>;
}
declare module 'deepstream.io/src/config/config-initialiser.js' {
  declare module.exports: $Exports<'deepstream.io/src/config/config-initialiser'>;
}
declare module 'deepstream.io/src/config/file-utils.js' {
  declare module.exports: $Exports<'deepstream.io/src/config/file-utils'>;
}
declare module 'deepstream.io/src/config/js-yaml-loader.js' {
  declare module.exports: $Exports<'deepstream.io/src/config/js-yaml-loader'>;
}
declare module 'deepstream.io/src/constants/constants.js' {
  declare module.exports: $Exports<'deepstream.io/src/constants/constants'>;
}
declare module 'deepstream.io/src/deepstream.io.js' {
  declare module.exports: $Exports<'deepstream.io/src/deepstream.io'>;
}
declare module 'deepstream.io/src/default-options.js' {
  declare module.exports: $Exports<'deepstream.io/src/default-options'>;
}
declare module 'deepstream.io/src/default-plugins/local-cache.js' {
  declare module.exports: $Exports<'deepstream.io/src/default-plugins/local-cache'>;
}
declare module 'deepstream.io/src/default-plugins/noop-message-connector.js' {
  declare module.exports: $Exports<'deepstream.io/src/default-plugins/noop-message-connector'>;
}
declare module 'deepstream.io/src/default-plugins/noop-storage.js' {
  declare module.exports: $Exports<'deepstream.io/src/default-plugins/noop-storage'>;
}
declare module 'deepstream.io/src/default-plugins/std-out-logger.js' {
  declare module.exports: $Exports<'deepstream.io/src/default-plugins/std-out-logger'>;
}
declare module 'deepstream.io/src/event/event-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/event/event-handler'>;
}
declare module 'deepstream.io/src/listen/listener-registry.js' {
  declare module.exports: $Exports<'deepstream.io/src/listen/listener-registry'>;
}
declare module 'deepstream.io/src/listen/listener-timeout-registry.js' {
  declare module.exports: $Exports<'deepstream.io/src/listen/listener-timeout-registry'>;
}
declare module 'deepstream.io/src/message/http/connection-endpoint.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/http/connection-endpoint'>;
}
declare module 'deepstream.io/src/message/http/server.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/http/server'>;
}
declare module 'deepstream.io/src/message/http/socket-wrapper.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/http/socket-wrapper'>;
}
declare module 'deepstream.io/src/message/jif-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/jif-handler'>;
}
declare module 'deepstream.io/src/message/message-builder.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/message-builder'>;
}
declare module 'deepstream.io/src/message/message-distributor.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/message-distributor'>;
}
declare module 'deepstream.io/src/message/message-parser.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/message-parser'>;
}
declare module 'deepstream.io/src/message/message-processor.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/message-processor'>;
}
declare module 'deepstream.io/src/message/uws/connection-endpoint.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/uws/connection-endpoint'>;
}
declare module 'deepstream.io/src/message/uws/socket-wrapper.js' {
  declare module.exports: $Exports<'deepstream.io/src/message/uws/socket-wrapper'>;
}
declare module 'deepstream.io/src/permission/config-compiler.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/config-compiler'>;
}
declare module 'deepstream.io/src/permission/config-permission-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/config-permission-handler'>;
}
declare module 'deepstream.io/src/permission/config-schema.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/config-schema'>;
}
declare module 'deepstream.io/src/permission/config-validator.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/config-validator'>;
}
declare module 'deepstream.io/src/permission/open-permission-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/open-permission-handler'>;
}
declare module 'deepstream.io/src/permission/path-parser.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/path-parser'>;
}
declare module 'deepstream.io/src/permission/rule-application.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/rule-application'>;
}
declare module 'deepstream.io/src/permission/rule-cache.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/rule-cache'>;
}
declare module 'deepstream.io/src/permission/rule-parser.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/rule-parser'>;
}
declare module 'deepstream.io/src/permission/rules-map.js' {
  declare module.exports: $Exports<'deepstream.io/src/permission/rules-map'>;
}
declare module 'deepstream.io/src/presence/presence-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/presence/presence-handler'>;
}
declare module 'deepstream.io/src/record/json-path.js' {
  declare module.exports: $Exports<'deepstream.io/src/record/json-path'>;
}
declare module 'deepstream.io/src/record/record-deletion.js' {
  declare module.exports: $Exports<'deepstream.io/src/record/record-deletion'>;
}
declare module 'deepstream.io/src/record/record-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/record/record-handler'>;
}
declare module 'deepstream.io/src/record/record-request.js' {
  declare module.exports: $Exports<'deepstream.io/src/record/record-request'>;
}
declare module 'deepstream.io/src/record/record-transition.js' {
  declare module.exports: $Exports<'deepstream.io/src/record/record-transition'>;
}
declare module 'deepstream.io/src/rpc/rpc-handler.js' {
  declare module.exports: $Exports<'deepstream.io/src/rpc/rpc-handler'>;
}
declare module 'deepstream.io/src/rpc/rpc-proxy.js' {
  declare module.exports: $Exports<'deepstream.io/src/rpc/rpc-proxy'>;
}
declare module 'deepstream.io/src/rpc/rpc.js' {
  declare module.exports: $Exports<'deepstream.io/src/rpc/rpc'>;
}
declare module 'deepstream.io/src/utils/dependency-initialiser.js' {
  declare module.exports: $Exports<'deepstream.io/src/utils/dependency-initialiser'>;
}
declare module 'deepstream.io/src/utils/read-message.js' {
  declare module.exports: $Exports<'deepstream.io/src/utils/read-message'>;
}
declare module 'deepstream.io/src/utils/subscription-registry.js' {
  declare module.exports: $Exports<'deepstream.io/src/utils/subscription-registry'>;
}
declare module 'deepstream.io/src/utils/utils.js' {
  declare module.exports: $Exports<'deepstream.io/src/utils/utils'>;
}
declare module 'deepstream.io/test-e2e/framework/client-handler.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/client-handler'>;
}
declare module 'deepstream.io/test-e2e/framework/client.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/client'>;
}
declare module 'deepstream.io/test-e2e/framework/event.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/event'>;
}
declare module 'deepstream.io/test-e2e/framework/listening.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/listening'>;
}
declare module 'deepstream.io/test-e2e/framework/presence.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/presence'>;
}
declare module 'deepstream.io/test-e2e/framework/record.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/record'>;
}
declare module 'deepstream.io/test-e2e/framework/rpc.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/rpc'>;
}
declare module 'deepstream.io/test-e2e/framework/utils.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/utils'>;
}
declare module 'deepstream.io/test-e2e/framework/world.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/framework/world'>;
}
declare module 'deepstream.io/test-e2e/steps/client/client-definition-step.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/client/client-definition-step'>;
}
declare module 'deepstream.io/test-e2e/steps/client/connection-steps.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/client/connection-steps'>;
}
declare module 'deepstream.io/test-e2e/steps/client/event-steps.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/client/event-steps'>;
}
declare module 'deepstream.io/test-e2e/steps/client/listening-steps.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/client/listening-steps'>;
}
declare module 'deepstream.io/test-e2e/steps/client/presence-steps.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/client/presence-steps'>;
}
declare module 'deepstream.io/test-e2e/steps/client/record-steps.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/client/record-steps'>;
}
declare module 'deepstream.io/test-e2e/steps/client/rpc-steps.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/client/rpc-steps'>;
}
declare module 'deepstream.io/test-e2e/steps/client/utils.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/client/utils'>;
}
declare module 'deepstream.io/test-e2e/steps/http/http-steps.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/http/http-steps'>;
}
declare module 'deepstream.io/test-e2e/steps/server/step-definition-server.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/steps/server/step-definition-server'>;
}
declare module 'deepstream.io/test-e2e/tools/cluster.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/tools/cluster'>;
}
declare module 'deepstream.io/test-e2e/tools/test-logger.js' {
  declare module.exports: $Exports<'deepstream.io/test-e2e/tools/test-logger'>;
}
declare module 'deepstream.io/test-protocol/run.js' {
  declare module.exports: $Exports<'deepstream.io/test-protocol/run'>;
}
declare module 'deepstream.io/test-protocol/src/client.js' {
  declare module.exports: $Exports<'deepstream.io/test-protocol/src/client'>;
}
declare module 'deepstream.io/test-protocol/src/row.js' {
  declare module.exports: $Exports<'deepstream.io/test-protocol/src/row'>;
}
declare module 'deepstream.io/test-protocol/src/server.js' {
  declare module.exports: $Exports<'deepstream.io/test-protocol/src/server'>;
}
declare module 'deepstream.io/test/authentication/file-based-authentication-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/authentication/file-based-authentication-handlerSpec'>;
}
declare module 'deepstream.io/test/authentication/http-authentication-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/authentication/http-authentication-handlerSpec'>;
}
declare module 'deepstream.io/test/authentication/open-authentication-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/authentication/open-authentication-handlerSpec'>;
}
declare module 'deepstream.io/test/bin/installerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/bin/installerSpec'>;
}
declare module 'deepstream.io/test/config/config-initialiserSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/config/config-initialiserSpec'>;
}
declare module 'deepstream.io/test/config/fileSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/config/fileSpec'>;
}
declare module 'deepstream.io/test/config/js-yaml-loaderSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/config/js-yaml-loaderSpec'>;
}
declare module 'deepstream.io/test/deepstreamioSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/deepstreamioSpec'>;
}
declare module 'deepstream.io/test/default-plugins/local-cacheSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/default-plugins/local-cacheSpec'>;
}
declare module 'deepstream.io/test/default-plugins/noop-storageSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/default-plugins/noop-storageSpec'>;
}
declare module 'deepstream.io/test/default-plugins/std-out-loggerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/default-plugins/std-out-loggerSpec'>;
}
declare module 'deepstream.io/test/event/event-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/event/event-handlerSpec'>;
}
declare module 'deepstream.io/test/event/event-listeningSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/event/event-listeningSpec'>;
}
declare module 'deepstream.io/test/http/http-endpointSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/http/http-endpointSpec'>;
}
declare module 'deepstream.io/test/http/jif-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/http/jif-handlerSpec'>;
}
declare module 'deepstream.io/test/listen/listener-register-local-timeoutsSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/listen/listener-register-local-timeoutsSpec'>;
}
declare module 'deepstream.io/test/listen/listener-registry-local-load-balancingSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/listen/listener-registry-local-load-balancingSpec'>;
}
declare module 'deepstream.io/test/listen/listener-registry-remote-load-balancingSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/listen/listener-registry-remote-load-balancingSpec'>;
}
declare module 'deepstream.io/test/listen/listener-registrySpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/listen/listener-registrySpec'>;
}
declare module 'deepstream.io/test/listen/listener-test-utils.js' {
  declare module.exports: $Exports<'deepstream.io/test/listen/listener-test-utils'>;
}
declare module 'deepstream.io/test/message/connection-endpoint-httpsSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/connection-endpoint-httpsSpec'>;
}
declare module 'deepstream.io/test/message/connection-endpointSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/connection-endpointSpec'>;
}
declare module 'deepstream.io/test/message/message-builderSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/message-builderSpec'>;
}
declare module 'deepstream.io/test/message/message-distributorSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/message-distributorSpec'>;
}
declare module 'deepstream.io/test/message/message-parserSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/message-parserSpec'>;
}
declare module 'deepstream.io/test/message/message-processorSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/message-processorSpec'>;
}
declare module 'deepstream.io/test/message/permission-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/permission-handlerSpec'>;
}
declare module 'deepstream.io/test/message/socket-wrapperSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/socket-wrapperSpec'>;
}
declare module 'deepstream.io/test/message/type-conversionSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/message/type-conversionSpec'>;
}
declare module 'deepstream.io/test/mocks/auth-handler-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/auth-handler-mock'>;
}
declare module 'deepstream.io/test/mocks/authentication-handler-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/authentication-handler-mock'>;
}
declare module 'deepstream.io/test/mocks/closable-logger.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/closable-logger'>;
}
declare module 'deepstream.io/test/mocks/http-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/http-mock'>;
}
declare module 'deepstream.io/test/mocks/logger-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/logger-mock'>;
}
declare module 'deepstream.io/test/mocks/message-connector-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/message-connector-mock'>;
}
declare module 'deepstream.io/test/mocks/perm-handler-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/perm-handler-mock'>;
}
declare module 'deepstream.io/test/mocks/permission-handler-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/permission-handler-mock'>;
}
declare module 'deepstream.io/test/mocks/plugin-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/plugin-mock'>;
}
declare module 'deepstream.io/test/mocks/socket-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/socket-mock'>;
}
declare module 'deepstream.io/test/mocks/socket-wrapper-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/socket-wrapper-mock'>;
}
declare module 'deepstream.io/test/mocks/storage-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/storage-mock'>;
}
declare module 'deepstream.io/test/mocks/uws-mock.js' {
  declare module.exports: $Exports<'deepstream.io/test/mocks/uws-mock'>;
}
declare module 'deepstream.io/test/permission/config-compilerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-compilerSpec'>;
}
declare module 'deepstream.io/test/permission/config-permission-handler-basicSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-permission-handler-basicSpec'>;
}
declare module 'deepstream.io/test/permission/config-permission-handler-createSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-permission-handler-createSpec'>;
}
declare module 'deepstream.io/test/permission/config-permission-handler-cross-referenceSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-permission-handler-cross-referenceSpec'>;
}
declare module 'deepstream.io/test/permission/config-permission-handler-loadSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-permission-handler-loadSpec'>;
}
declare module 'deepstream.io/test/permission/config-permission-handler-nested-cross-referenceSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-permission-handler-nested-cross-referenceSpec'>;
}
declare module 'deepstream.io/test/permission/config-permission-handler-otherSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-permission-handler-otherSpec'>;
}
declare module 'deepstream.io/test/permission/config-permission-handler-record-patchSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-permission-handler-record-patchSpec'>;
}
declare module 'deepstream.io/test/permission/config-validatorSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/config-validatorSpec'>;
}
declare module 'deepstream.io/test/permission/open-permission-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/open-permission-handlerSpec'>;
}
declare module 'deepstream.io/test/permission/path-parserSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/path-parserSpec'>;
}
declare module 'deepstream.io/test/permission/rule-cacheSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/rule-cacheSpec'>;
}
declare module 'deepstream.io/test/permission/rule-parserSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/rule-parserSpec'>;
}
declare module 'deepstream.io/test/permission/rules-mapSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/permission/rules-mapSpec'>;
}
declare module 'deepstream.io/test/presence/presence-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/presence/presence-handlerSpec'>;
}
declare module 'deepstream.io/test/record/json-pathSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/record/json-pathSpec'>;
}
declare module 'deepstream.io/test/record/record-deletionSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/record/record-deletionSpec'>;
}
declare module 'deepstream.io/test/record/record-handler-permissionSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/record/record-handler-permissionSpec'>;
}
declare module 'deepstream.io/test/record/record-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/record/record-handlerSpec'>;
}
declare module 'deepstream.io/test/record/record-listeningSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/record/record-listeningSpec'>;
}
declare module 'deepstream.io/test/record/record-requestSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/record/record-requestSpec'>;
}
declare module 'deepstream.io/test/record/record-transitionSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/record/record-transitionSpec'>;
}
declare module 'deepstream.io/test/record/record-write-acknowledgementSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/record/record-write-acknowledgementSpec'>;
}
declare module 'deepstream.io/test/rpc/rpc-handler-reroutingSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/rpc/rpc-handler-reroutingSpec'>;
}
declare module 'deepstream.io/test/rpc/rpc-handlerSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/rpc/rpc-handlerSpec'>;
}
declare module 'deepstream.io/test/rpc/rpc-proxySpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/rpc/rpc-proxySpec'>;
}
declare module 'deepstream.io/test/rpc/rpcSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/rpc/rpcSpec'>;
}
declare module 'deepstream.io/test/test-configs/config-broken.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-configs/config-broken'>;
}
declare module 'deepstream.io/test/test-configs/config.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-configs/config'>;
}
declare module 'deepstream.io/test/test-configs/exists-test/a-file.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-configs/exists-test/a-file'>;
}
declare module 'deepstream.io/test/test-helper/custom-logger.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-helper/custom-logger'>;
}
declare module 'deepstream.io/test/test-helper/start-test-server.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-helper/start-test-server'>;
}
declare module 'deepstream.io/test/test-helper/test-helper.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-helper/test-helper'>;
}
declare module 'deepstream.io/test/test-helper/test-http-server.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-helper/test-http-server'>;
}
declare module 'deepstream.io/test/test-plugins/deepstream.io-connection-http.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-plugins/deepstream.io-connection-http'>;
}
declare module 'deepstream.io/test/test-plugins/plugin-a.js' {
  declare module.exports: $Exports<'deepstream.io/test/test-plugins/plugin-a'>;
}
declare module 'deepstream.io/test/utils/dependency-initialiserSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/utils/dependency-initialiserSpec'>;
}
declare module 'deepstream.io/test/utils/read-messageSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/utils/read-messageSpec'>;
}
declare module 'deepstream.io/test/utils/subscription-registrySpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/utils/subscription-registrySpec'>;
}
declare module 'deepstream.io/test/utils/utilsSpec.js' {
  declare module.exports: $Exports<'deepstream.io/test/utils/utilsSpec'>;
}
