// flow-typed signature: 62f21e34038d90c5eba7ef6868900ac1
// flow-typed version: <<STUB>>/eslint-config-bunchtogether_v^1.1.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-bunchtogether'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-bunchtogether' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-bunchtogether/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/browser' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/imports' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/jsx-ally' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/mocha' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/rules/variables' {
  declare module.exports: any;
}

declare module 'eslint-config-bunchtogether/test/test-base' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-bunchtogether/index' {
  declare module.exports: $Exports<'eslint-config-bunchtogether'>;
}
declare module 'eslint-config-bunchtogether/index.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether'>;
}
declare module 'eslint-config-bunchtogether/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/best-practices'>;
}
declare module 'eslint-config-bunchtogether/rules/browser.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/browser'>;
}
declare module 'eslint-config-bunchtogether/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/errors'>;
}
declare module 'eslint-config-bunchtogether/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/es6'>;
}
declare module 'eslint-config-bunchtogether/rules/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/flowtype'>;
}
declare module 'eslint-config-bunchtogether/rules/imports.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/imports'>;
}
declare module 'eslint-config-bunchtogether/rules/jsx-ally.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/jsx-ally'>;
}
declare module 'eslint-config-bunchtogether/rules/mocha.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/mocha'>;
}
declare module 'eslint-config-bunchtogether/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/node'>;
}
declare module 'eslint-config-bunchtogether/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/react'>;
}
declare module 'eslint-config-bunchtogether/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/strict'>;
}
declare module 'eslint-config-bunchtogether/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/style'>;
}
declare module 'eslint-config-bunchtogether/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/rules/variables'>;
}
declare module 'eslint-config-bunchtogether/test/test-base.js' {
  declare module.exports: $Exports<'eslint-config-bunchtogether/test/test-base'>;
}
