// flow-typed signature: 86e42dac6d6f3d6a23a3a1a3a896f4ad
// flow-typed version: <<STUB>>/expect_v^23.6.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expect/build-es5/index' {
  declare module.exports: any;
}

declare module 'expect/build/asymmetric_matchers' {
  declare module.exports: any;
}

declare module 'expect/build/extract_expected_assertions_errors' {
  declare module.exports: any;
}

declare module 'expect/build/fake_chalk' {
  declare module.exports: any;
}

declare module 'expect/build/index' {
  declare module.exports: any;
}

declare module 'expect/build/jasmine_utils' {
  declare module.exports: any;
}

declare module 'expect/build/jest_matchers_object' {
  declare module.exports: any;
}

declare module 'expect/build/matchers' {
  declare module.exports: any;
}

declare module 'expect/build/spy_matchers' {
  declare module.exports: any;
}

declare module 'expect/build/to_throw_matchers' {
  declare module.exports: any;
}

declare module 'expect/build/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expect/build-es5/index.js' {
  declare module.exports: $Exports<'expect/build-es5/index'>;
}
declare module 'expect/build/asymmetric_matchers.js' {
  declare module.exports: $Exports<'expect/build/asymmetric_matchers'>;
}
declare module 'expect/build/extract_expected_assertions_errors.js' {
  declare module.exports: $Exports<'expect/build/extract_expected_assertions_errors'>;
}
declare module 'expect/build/fake_chalk.js' {
  declare module.exports: $Exports<'expect/build/fake_chalk'>;
}
declare module 'expect/build/index.js' {
  declare module.exports: $Exports<'expect/build/index'>;
}
declare module 'expect/build/jasmine_utils.js' {
  declare module.exports: $Exports<'expect/build/jasmine_utils'>;
}
declare module 'expect/build/jest_matchers_object.js' {
  declare module.exports: $Exports<'expect/build/jest_matchers_object'>;
}
declare module 'expect/build/matchers.js' {
  declare module.exports: $Exports<'expect/build/matchers'>;
}
declare module 'expect/build/spy_matchers.js' {
  declare module.exports: $Exports<'expect/build/spy_matchers'>;
}
declare module 'expect/build/to_throw_matchers.js' {
  declare module.exports: $Exports<'expect/build/to_throw_matchers'>;
}
declare module 'expect/build/utils.js' {
  declare module.exports: $Exports<'expect/build/utils'>;
}
