// flow-typed signature: 8461192abc7b5a04b90eb0f45bc20454
// flow-typed version: <<STUB>>/jest-flow-transform_v^1.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-flow-transform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-flow-transform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-flow-transform/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-flow-transform/index' {
  declare module.exports: $Exports<'jest-flow-transform'>;
}
declare module 'jest-flow-transform/index.js' {
  declare module.exports: $Exports<'jest-flow-transform'>;
}
declare module 'jest-flow-transform/index.test.js' {
  declare module.exports: $Exports<'jest-flow-transform/index.test'>;
}
