// flow-typed signature: 5c6a4b59a019adfec8b992875bbea79c
// flow-typed version: <<STUB>>/nanomsg_v^3.3.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nanomsg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nanomsg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nanomsg/examples/multisub' {
  declare module.exports: any;
}

declare module 'nanomsg/examples/pipeline' {
  declare module.exports: any;
}

declare module 'nanomsg/examples/pubsub' {
  declare module.exports: any;
}

declare module 'nanomsg/examples/reqrep' {
  declare module.exports: any;
}

declare module 'nanomsg/examples/transforms' {
  declare module.exports: any;
}

declare module 'nanomsg/examples/writablepipe' {
  declare module.exports: any;
}

declare module 'nanomsg/examples/ws/server' {
  declare module.exports: any;
}

declare module 'nanomsg/lib/index' {
  declare module.exports: any;
}

declare module 'nanomsg/perf/common' {
  declare module.exports: any;
}

declare module 'nanomsg/perf/local_lat' {
  declare module.exports: any;
}

declare module 'nanomsg/perf/local_thr' {
  declare module.exports: any;
}

declare module 'nanomsg/perf/remote_lat' {
  declare module.exports: any;
}

declare module 'nanomsg/perf/remote_thr' {
  declare module.exports: any;
}

declare module 'nanomsg/test/bind' {
  declare module.exports: any;
}

declare module 'nanomsg/test/bug105' {
  declare module.exports: any;
}

declare module 'nanomsg/test/chan' {
  declare module.exports: any;
}

declare module 'nanomsg/test/close' {
  declare module.exports: any;
}

declare module 'nanomsg/test/connect' {
  declare module.exports: any;
}

declare module 'nanomsg/test/inproc' {
  declare module.exports: any;
}

declare module 'nanomsg/test/ipc' {
  declare module.exports: any;
}

declare module 'nanomsg/test/pushstress' {
  declare module.exports: any;
}

declare module 'nanomsg/test/send' {
  declare module.exports: any;
}

declare module 'nanomsg/test/shutdown' {
  declare module.exports: any;
}

declare module 'nanomsg/test/sockoptapi' {
  declare module.exports: any;
}

declare module 'nanomsg/test/standalone/device' {
  declare module.exports: any;
}

declare module 'nanomsg/test/standalone/device2' {
  declare module.exports: any;
}

declare module 'nanomsg/test/standalone/device3' {
  declare module.exports: any;
}

declare module 'nanomsg/test/standalone/term' {
  declare module.exports: any;
}

declare module 'nanomsg/test/streams' {
  declare module.exports: any;
}

declare module 'nanomsg/test/symbol' {
  declare module.exports: any;
}

declare module 'nanomsg/test/symbolinfo' {
  declare module.exports: any;
}

declare module 'nanomsg/test/symbols' {
  declare module.exports: any;
}

declare module 'nanomsg/test/tcp' {
  declare module.exports: any;
}

declare module 'nanomsg/test/test' {
  declare module.exports: any;
}

declare module 'nanomsg/test/transform' {
  declare module.exports: any;
}

declare module 'nanomsg/test/ws' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nanomsg/examples/multisub.js' {
  declare module.exports: $Exports<'nanomsg/examples/multisub'>;
}
declare module 'nanomsg/examples/pipeline.js' {
  declare module.exports: $Exports<'nanomsg/examples/pipeline'>;
}
declare module 'nanomsg/examples/pubsub.js' {
  declare module.exports: $Exports<'nanomsg/examples/pubsub'>;
}
declare module 'nanomsg/examples/reqrep.js' {
  declare module.exports: $Exports<'nanomsg/examples/reqrep'>;
}
declare module 'nanomsg/examples/transforms.js' {
  declare module.exports: $Exports<'nanomsg/examples/transforms'>;
}
declare module 'nanomsg/examples/writablepipe.js' {
  declare module.exports: $Exports<'nanomsg/examples/writablepipe'>;
}
declare module 'nanomsg/examples/ws/server.js' {
  declare module.exports: $Exports<'nanomsg/examples/ws/server'>;
}
declare module 'nanomsg/lib/index.js' {
  declare module.exports: $Exports<'nanomsg/lib/index'>;
}
declare module 'nanomsg/perf/common.js' {
  declare module.exports: $Exports<'nanomsg/perf/common'>;
}
declare module 'nanomsg/perf/local_lat.js' {
  declare module.exports: $Exports<'nanomsg/perf/local_lat'>;
}
declare module 'nanomsg/perf/local_thr.js' {
  declare module.exports: $Exports<'nanomsg/perf/local_thr'>;
}
declare module 'nanomsg/perf/remote_lat.js' {
  declare module.exports: $Exports<'nanomsg/perf/remote_lat'>;
}
declare module 'nanomsg/perf/remote_thr.js' {
  declare module.exports: $Exports<'nanomsg/perf/remote_thr'>;
}
declare module 'nanomsg/test/bind.js' {
  declare module.exports: $Exports<'nanomsg/test/bind'>;
}
declare module 'nanomsg/test/bug105.js' {
  declare module.exports: $Exports<'nanomsg/test/bug105'>;
}
declare module 'nanomsg/test/chan.js' {
  declare module.exports: $Exports<'nanomsg/test/chan'>;
}
declare module 'nanomsg/test/close.js' {
  declare module.exports: $Exports<'nanomsg/test/close'>;
}
declare module 'nanomsg/test/connect.js' {
  declare module.exports: $Exports<'nanomsg/test/connect'>;
}
declare module 'nanomsg/test/inproc.js' {
  declare module.exports: $Exports<'nanomsg/test/inproc'>;
}
declare module 'nanomsg/test/ipc.js' {
  declare module.exports: $Exports<'nanomsg/test/ipc'>;
}
declare module 'nanomsg/test/pushstress.js' {
  declare module.exports: $Exports<'nanomsg/test/pushstress'>;
}
declare module 'nanomsg/test/send.js' {
  declare module.exports: $Exports<'nanomsg/test/send'>;
}
declare module 'nanomsg/test/shutdown.js' {
  declare module.exports: $Exports<'nanomsg/test/shutdown'>;
}
declare module 'nanomsg/test/sockoptapi.js' {
  declare module.exports: $Exports<'nanomsg/test/sockoptapi'>;
}
declare module 'nanomsg/test/standalone/device.js' {
  declare module.exports: $Exports<'nanomsg/test/standalone/device'>;
}
declare module 'nanomsg/test/standalone/device2.js' {
  declare module.exports: $Exports<'nanomsg/test/standalone/device2'>;
}
declare module 'nanomsg/test/standalone/device3.js' {
  declare module.exports: $Exports<'nanomsg/test/standalone/device3'>;
}
declare module 'nanomsg/test/standalone/term.js' {
  declare module.exports: $Exports<'nanomsg/test/standalone/term'>;
}
declare module 'nanomsg/test/streams.js' {
  declare module.exports: $Exports<'nanomsg/test/streams'>;
}
declare module 'nanomsg/test/symbol.js' {
  declare module.exports: $Exports<'nanomsg/test/symbol'>;
}
declare module 'nanomsg/test/symbolinfo.js' {
  declare module.exports: $Exports<'nanomsg/test/symbolinfo'>;
}
declare module 'nanomsg/test/symbols.js' {
  declare module.exports: $Exports<'nanomsg/test/symbols'>;
}
declare module 'nanomsg/test/tcp.js' {
  declare module.exports: $Exports<'nanomsg/test/tcp'>;
}
declare module 'nanomsg/test/test.js' {
  declare module.exports: $Exports<'nanomsg/test/test'>;
}
declare module 'nanomsg/test/transform.js' {
  declare module.exports: $Exports<'nanomsg/test/transform'>;
}
declare module 'nanomsg/test/ws.js' {
  declare module.exports: $Exports<'nanomsg/test/ws'>;
}
