// flow-typed signature: a91995962d3f3f5afb8cbf1b09862df6
// flow-typed version: <<STUB>>/nanomsg-cluster_v^0.4.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nanomsg-cluster'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nanomsg-cluster' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nanomsg-cluster/dist/index' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint-config-bunchtogether_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/expect_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/ip_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/jest_v21.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/jest-directory-named-resolver_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/jest-flow-transform_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/mocha_v4.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/nanomsg_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/node-discover_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/nyc_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/pre-commit_vx.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/flow-typed/npm/uuid_v3.x.x' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/src/index' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/tests/cluster-exception.test' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/tests/discovery.test' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/tests/lib/node' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/tests/messaging.test' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/tests/peers.test' {
  declare module.exports: any;
}

declare module 'nanomsg-cluster/tests/pipeline.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nanomsg-cluster/dist/index.js' {
  declare module.exports: $Exports<'nanomsg-cluster/dist/index'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/cross-env_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint-config-bunchtogether_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint-config-bunchtogether_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint-import-resolver-webpack_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-jest_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint-plugin-jest_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/expect_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/expect_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/ip_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/ip_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/jest_v21.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/jest_v21.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/jest-directory-named-resolver_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/jest-directory-named-resolver_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/jest-flow-transform_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/jest-flow-transform_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/mocha_v4.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/mocha_v4.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/nanomsg_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/nanomsg_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/node-discover_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/node-discover_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/nyc_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/nyc_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/pre-commit_vx.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/pre-commit_vx.x.x'>;
}
declare module 'nanomsg-cluster/flow-typed/npm/uuid_v3.x.x.js' {
  declare module.exports: $Exports<'nanomsg-cluster/flow-typed/npm/uuid_v3.x.x'>;
}
declare module 'nanomsg-cluster/src/index.js' {
  declare module.exports: $Exports<'nanomsg-cluster/src/index'>;
}
declare module 'nanomsg-cluster/tests/cluster-exception.test.js' {
  declare module.exports: $Exports<'nanomsg-cluster/tests/cluster-exception.test'>;
}
declare module 'nanomsg-cluster/tests/discovery.test.js' {
  declare module.exports: $Exports<'nanomsg-cluster/tests/discovery.test'>;
}
declare module 'nanomsg-cluster/tests/lib/node.js' {
  declare module.exports: $Exports<'nanomsg-cluster/tests/lib/node'>;
}
declare module 'nanomsg-cluster/tests/messaging.test.js' {
  declare module.exports: $Exports<'nanomsg-cluster/tests/messaging.test'>;
}
declare module 'nanomsg-cluster/tests/peers.test.js' {
  declare module.exports: $Exports<'nanomsg-cluster/tests/peers.test'>;
}
declare module 'nanomsg-cluster/tests/pipeline.test.js' {
  declare module.exports: $Exports<'nanomsg-cluster/tests/pipeline.test'>;
}
